alias :e="nvim"  # Somtimes I type this thinking that I am inside vim :P
alias :q="exit"
alias :wq="exit"
alias c='xclip -select c'
alias d="docker"
alias dc="docker-compose"
alias dm="docker-machine"
alias e="nvim"
alias ff="firefox"
alias g="git"
alias p="python"
alias q="exit"
alias ssn="sudo shutdown now"
alias sudo='sudo '  # Enable aliases to be sudo’ed
alias t="tmux"
alias y="yarn"
alias z="zellij"
alias docker-desktop="systemctl --user start docker-desktop"
